name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.4', '2.5']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install cURL Headers
        run: sudo apt-get install libcurl4-openssl-dev
      - uses: ruby/setup-ruby@v1
        with:
          bundler:  1.17.3
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Run the tests
        run: bundle exec rake
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cURL Headers
        run: sudo apt-get install libcurl4-openssl-dev
      - uses: ruby/setup-ruby@v1
        with:
          bundler:  1.17.3
          bundler-cache: true
          ruby-version: 2.5
      - name: Install dependencies
        run: bundle install
      - name: Run the tests
        run: bundle exec standardrb
